version: '3.8'
services:
  #########################################
  #   Setup Database container
  #########################################
  database:
    container_name: database-dev
    image: mysql:8.3.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"
    volumes:
      - db:/var/lib/mysql
    networks:
      - server-dev
  #########################################
  #   Setup Backend container
  #########################################
  backend:
    depends_on:
      - database
    container_name: backend-dev
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_BACKEND_IMAGE}
    build:
      context: ./backend
      target: development
    environment:
      - BACKEND_CONTAINER_PORT=${BACKEND_CONTAINER_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_CONTAINER_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - FRONTEND_HOST_DOMAIN=${FRONTEND_HOST_DOMAIN}
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
    volumes:
      - type: bind
        source: ./backend
        target: /app
    command: npm run start:dev
    networks:
      - server-dev
  #########################################
  #   Setup Frontend container
  #########################################
  frontend:
    depends_on:
      - backend
    container_name: frontend-dev
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_FRONTEND_IMAGE}
    build:
      context: ./frontend
      target: development
    environment:
      - NEXT_PUBLIC_BACKEND_HOST_DOMAIN=${BACKEND_HOST_DOMAIN}
    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    command: npm run dev
volumes:
  db:
networks:
  server-dev:
