version: '3.8'
services:
  #########################################
  #   Setup Database container
  #########################################
  database:
    container_name: database-prod
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_DB_IMAGE}
    build:
      context: ./database
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"
    volumes:
      - db:/var/lib/mysql
    networks:
      - server
  #########################################
  #   Setup Backend container
  #########################################
  backend:
    depends_on:
      - database
    container_name: backend-prod
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_BACKEND_IMAGE}
    build:
      context: ./backend
      target: production
      args:
        - BACKEND_CONTAINER_PORT=${BACKEND_CONTAINER_PORT}
        - MYSQL_HOST=${MYSQL_HOST}
        - MYSQL_PORT=${MYSQL_CONTAINER_PORT}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - FRONTEND_HOST_DOMAIN=${FRONTEND_HOST_DOMAIN}
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
    networks:
      - server
volumes:
  db:
networks:
  server:
