name: staging_pr_database_cd_pipeline

on:
  workflow_run:
    workflows: ["staging_pr_database_ci_pipeline"]
    types:
      - completed
  repository_dispatch:
jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Create a network for staging-pr
      run: echo ${{secrets.SHH_USER_PASSWORD}} | sudo -S docker network create staging-pr-network
    - name: Pull Docker image
      run: echo ${{secrets.SHH_USER_PASSWORD}} | sudo -S docker pull ${{secrets.DOCKER_HUB_USERNAME}}/${{secrets.DOCKER_HUB_DB_IMAGE_STAGING_PR}}:latest
    - name: Stop old docker container
      run: echo ${{secrets.SHH_USER_PASSWORD}} | sudo -S docker stop database-staging-pr || true
    - name: Run Docker Container
      run: echo ${{secrets.SHH_USER_PASSWORD}} | sudo -S docker run -rm -d -p ${{secrets.MYSQL_HOST_PORT_STAGING_PR}}:${{secrets.MYSQL_CONTAINER_PORT_STAGING_PR}} --name database-staging-pr -v db-staging-pr:/var/lib/mysql --network staging-pr-network ${{secrets.DOCKER_HUB_USERNAME}}/${{secrets.DOCKER_HUB_DB_IMAGE_STAGING_PR}}
