name: staging_pr_database_cd_pipeline

on:
  pull_request:
    types:
      - opened
    branches:
      - 'staging'
    paths:
      - 'backend/**'
  workflow_dispatch:
jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Create a network for staging-pr
      run: echo ${{secrets.SHH_USER_PASSWORD}} | sudo -S docker network create staging-pr-network || true
    - name: Stop old docker container
      run: echo ${{secrets.SHH_USER_PASSWORD}} | sudo -S docker stop database-staging-pr || true
    - name: Run Docker Container
      run: |
        echo ${{secrets.SHH_USER_PASSWORD}} | sudo -S docker run --rm -d \
          --name ${{secrets.MYSQL_HOST_STAGING_PR}} \
          -v /var/lib/mysql \
          -e MYSQL_DATABASE=${{secrets.MYSQL_DATABASE_STAGING_PR}} \
          -e MYSQL_USER=${{secrets.MYSQL_USER_STAGING_PR}} \
          -e MYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD_STAGING_PR}} \
          -e MYSQL_ROOT_PASSWORD=${{secrets.MYSQL_ROOT_PASSWORD_STAGING_PR}} \
          --network staging-pr-network \
          mysql:8.3.0
