# name: staging_pr_backend_ci_pipeline

# on:
#   workflow_run:
#     workflows: ["staging_pr_database_cd_pipeline"]
#     types:
#       - completed
#   workflow_dispatch:
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         ref: ${{ github.ref }}
#     - name: Login Dockerhub
#       env:
#         DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
#         DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
#       run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      
#     - name: Build the Docker image
#       run: docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/${{secrets.DOCKER_HUB_BACKEND_IMAGE_STAGING_PR}} ./backend
           
#     - name: Push to Dockerhub
#       run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/${{secrets.DOCKER_HUB_BACKEND_IMAGE_STAGING_PR}}:latest
